hachyderm/community

corporate-accounts.md

I think this is a closer match to the biblical original, but that might not have been what you were going for. Just close this if not useful. ❤️

Fix grammar/spelling of "Do unto others…"

---

open-source-accounts.md

Typo: Open source accounts

---

mods/README.md

I added myself in the list sorted by language, hope that makes sense.

Add jakesmolka as translation volunteer for German

---

mods/README.md

Added mnl (slono on discord) as french/german translation volunteer
(I am a native speaker in both).

Added mnl as french/german translation volunteer

---

community.hachyderm.io/content/en/_index.html

Signed-off-by: Kris Nóva <kris@nivenly.com>

Testing deploy with new language

---

community.hachyderm.io/content/en/about/_index.html

Rest looks good to me on that page, but I'm not exactly native.

fix typo: margianlised

---

community.hachyderm.io/content/en/blog/posts/2022-12-03-leaving-the-basement/index.md

I really love when people's blog posts are on GitHub instead of stuffed only in a database, because then I can submit patches for the posts. :D

Fix blog typo

---

community.hachyderm.io/README.md

I pulled down the repo to look at the `https://community.hachyderm.io/` site. I had to `cd` into a different directory than was listed in the docs and also had to install hugo before I could work with it. 
I updated the readme to reflect that. 
(I'm still new to contributing. Please let me know if I'm doing this wrong.)

Add note about needing hugo

---

community.hachyderm.io/content/en/docs/account-types/_index.md

Test for deploy

---

community.hachyderm.io/README.md
community.hachyderm.io/content/en/docs/blocklists/.smbdeleteAAA3cf11
community.hachyderm.io/content/en/docs/blocklists/.smbdeleteAAA3cf15
community.hachyderm.io/content/en/docs/blocklists/.smbdeleteAAA3cf19
community.hachyderm.io/content/en/docs/blocklists/.smbdeleteAAA3cf1d
community.hachyderm.io/content/en/docs/blocklists/.smbdeleteAAA3cf21
community.hachyderm.io/content/en/docs/blocklists/_index.md

Adding documentation for the Blocklist

Blocklist documentation

---

community.hachyderm.io/config.toml

clicked through all of the docs pages, didn't see any breakage… and hello from treehouse.systems!

enable emoji

---

community.hachyderm.io/content/en/docs/nsfw-policy/_index.md

There != their would be the simplest fix, but I thought a slight rewording might appropriately fix the typo.
I can update this pull request, if requested during review.
Similarly, feel free to edit / close this PR however you would like - I'm not terribly keen on the phrasing "these individuals", but it is better than "those individuals".
Perhaps the simplest fix would be best, but that is your call :)

Fix typo and add danger emphasis to nsfw_policy

---

community.hachyderm.io/content/en/docs/account-types/bot-accounts/_index.md

Updates to resolve [moderation issue](https://github.com/hachyderm/moderation/issues/16)

Update bot rules and image alt tag

---

community.hachyderm.io/go.mod
community.hachyderm.io/go.sum

Updating docsy@0.5.1 to docsy@0.6.0

---

mods/README.md

- My editor decided to trim trailing whitespace as well, apparently. 😩

mods/README: Volunteer `issyl0` to assist with French post moderation

---

community.hachyderm.io/content/en/docs/reporting/_index.md

This one is meatballs, not hamburger.

Correct name for the "more" menu to report a post

---

community.hachyderm.io/content/en/docs/blocklists/_index.md

Fixed typo on Blocklist page

---

.github/ISSUE_TEMPLATE/9.Specialized-Account-Approvals.yml
community.hachyderm.io/content/en/approved/_index.md
community.hachyderm.io/content/en/docs/account-types/verification.md

Minor label / language chagnes

Change issue url

---

community.hachyderm.io/content/en/approved/_index.md

Added Tailscale as a verified, corporate account

Added Tailscale

---

community.hachyderm.io/content/en/approved/_index.md

Testing with mine to see if it works

Testing with user approval

---

community.hachyderm.io/content/en/approved/_index.md

Testing with Barnaby

---

community.hachyderm.io/content/en/approved/_index.md
community.hachyderm.io/content/en/docs/account-types/verification.md

Updated instructions and removed test

Added clarification to verification process

---

community.hachyderm.io/content/en/approved/_index.md

Adding coveragepy https://github.com/nedbat/coveragepy

Added coveragepy

---

community.hachyderm.io/content/en/approved/_index.md

Adding ADMIN Magazine
https://github.com/hachyderm/community/issues/307

Added ADMIN Magazine

---

community.hachyderm.io/content/en/docs/account-types/_index.md
community.hachyderm.io/content/en/docs/account-types/corporate-accounts.md
community.hachyderm.io/content/en/docs/account-types/open-source-accounts.md

Added pricing structure and removed Nivenly Trade Membership requirement

Corporate account updates

---

community.hachyderm.io/content/en/docs/account-types/influencer-accounts.md

Add a link to the nivenly discord

---

community.hachyderm.io/content/en/docs/account-types/_index.md
community.hachyderm.io/content/en/docs/moderation/exceptions-and-rules/_index.md

These changes provide visibility into the exceptions that would result in a general account being moderated more strictly. This also includes the first draft of the rules exception and rules change documentation.

General Accounts Update plus Rule Changes/Exceptions

---

mods/README.md

- I've not been called on since adding myself and realistically I don't have time.

README: Remove Issy from translation assistance mods

---

community.hachyderm.io/config.toml
community.hachyderm.io/content/en/docs/moderation/actions-and-appeals/_index.md
community.hachyderm.io/content/en/docs/monetary-posts/_index.md

This documentation will cover the best practices around mutual aid, charity fundraisers, affiliate links, and crowdfunding.

Generate documenation around "Monetary Posts"

---

community.hachyderm.io/content/en/docs/account-types/_index.md

fix 404 for ../nsfw-policy

---

community.hachyderm.io/content/en/approved/_index.md

Specialized Accounts: fluiddyn

---

community.hachyderm.io/content/en/approved/_index.md

Added Humane Guild to specialized accounts

Added Humane Guild

---

community.hachyderm.io/content/en/approved/_index.md

Tiny nit, DigitalOcean is a single word without a space :) Ty!

DigitalOcean has no space

---

community.hachyderm.io/content/en/approved/_index.md

Added ProjectJupyter

---

community.hachyderm.io/content/en/approved/_index.md

Added PGH Summit Event (Jan 2024)

PGH (Pittsburg) Racial Justice Summit

---

community.hachyderm.io/content/en/approved/_index.md

Added the status_updates parody account

Status Updates Parody Account

---

community.hachyderm.io/content/en/approved/_index.md

Added Determinate Systems

---

README.md

Fix for #543 markdown links in README invalid.

Update README.md fixes #543

---

community.hachyderm.io/content/en/approved/_index.md

Added the FediTo project as a project account #542

Added FediTo

---

community.hachyderm.io/content/en/docs/thank-you/_index.md

Removed references to Nóva on donations

---

community.hachyderm.io/content/en/docs/_index.md

URL: `.../docs/#i-would-like-to-know-why-a-user-or-instance-was-moderated-how-do-i-reach-out-and-what-can-i-expect`

Added section about how to ask about moderation

---

community.hachyderm.io/content/en/blog/announcements/2025-04-pixelfed/index.md

Blog post for the Pixelfed CVE.

Pixelfed CVE announcement

---

community.hachyderm.io/content/en/approved/_index.md

Added [OMNIBOR](https://omnibor.io/)

Added OMNIBOR
