hachyderm/community

corporate-accounts.md

Fix typos :
- "self-identify" should have a hyphen
- "anti-capitalists" should have a hyphen
- "Ultimatley" -> "Ultimately"
- "repetive" -> "repetitive"

chore: fix typos in corporate accounts doc

---

open-source-accounts.md

One of the projects I'd like to bring here is called "[Project] Community Edition".  It is completely open source and always has been, and is not an "up-sell" or "upgrade to pro" project, and there is no non-community-edition version. It is called community edition because it was taken over by the community after the company that used to maintain it stepped back (but it was always fully open source).
I think that `"up-sell" or "upgrade-to-pro"` covers what you are saying without unintentionally blocking legitimate community projects.
Thanks for considering.

"community edition" is not always a bad thing.

---

welcome/README.md

Saw a comment that this was broken and happened to be reading the docs so thought I'd help out.
[Rendered](https://github.com/hachyderm/community/blob/293320ef09e89272394eb981fce1276a7dcc0682/welcome/README.md) version seems to respect the relative path. Could also do the [raw URL](https://raw.githubusercontent.com/hachyderm/community/main/assets/mastodon-toot-visibility-flowchart.jpg) to serve it from a CDN, but that would always link to the main branch version.

Fix image link on welcome page

---

verification.md

Unfortunately, only personal GitHub profiles can be verified by adding the Mastodon profile to the website field. This solution does not apply for organizational accounts.

Clarify that verifying GitHub profiles only works for personal GitHub accounts

---

verification.md

I restated the paragraph _How long does verification persist?_ as one is free to change back the website on the GitHub profile as long as no changes are made to the Mastodon profile. See the referenced article for more details.

Restate paragraph on persistence of verified identities

---

verification.md

Fixes #62.
Originally I'd had a writeup of the "github switcheroo" in here, but @untitaker pointed out, and I verified, that it prevents other instances from verifying you when users on those instances view your profile there, so I've taken that back out.

Add caveats to verification instructions

---

.github/workflows/publish.yml

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-when-a-pull-request-merges
Desired outcome - the following will trigger build and deploy:
- PRs closed and merged to default brain (`main`)
- Pushes directly to default branch (`main`)
- Manual triggers of the action via GitHub UI**
** - note - I'm not 100% sure of the `event_name = 'workflow_dispatch'` piece. I wasn't able to find documentation, but it seems logical based on other examples!

Attempt to fix build+deploy on merge to main

---

.github/workflows/publish.yml

Following up to #159 - Maybe things will be happier with this syntax?
I am unclear why it did not like that syntax. My read of the docs indicates that should have worked:
https://docs.github.com/en/actions/learn-github-actions/expressions#about-expressions
Some searches of other GitHub actions files reveal that it might be wise to use `${{ }}` for `if` statements:
https://github.com/gabriel-miranda/next.js/blob/f8fb6c7a57fb209dc2f0438110cd8a723cb157d1/.github/workflows/build_native.yml#L55
I've also swapped out the event_name match for a `contains` function, so filtering other event types are more straightforward if adding other event types is desired.

Fix build + deploy

---

community.hachyderm.io/config.toml

Currently, it looks like the links to GitHub are not correct. This is because Hugo supposes that the documentation directory exists on the root directory of the GitHub repository.
This PR adjusts this path mismatch by adding the `github_subdir` config in `config.toml`.
ref. [Repository Links | Docsy](https://www.docsy.dev/docs/adding-content/repository-links/#github_subdir-optional)

fix(config.toml): fix broken links on the right sidebar

---

community.hachyderm.io/content/en/blog/announcements/2022-12-04-registrations/index.md

There was an extra ')' that messed up the link.

fix: Growth and Sustainability link

---

.markdownlint.yaml
verification.md

Add `.markdownlint.yaml` and ignore `MD025` and `MD036` (since it seems that we're okay with these). Fix the spelling of "GitHub" (it's a compound word) and use the leading "Note:" style, tidies up #71.

Markdown linting and grammar fixes to #71

---

community.hachyderm.io/config.toml

Hi! Leaving `baseURL` set to `/` works for links on the community site, but links in RSS feeds are broken and the feeds themselves do not validate.
Setting `baseURL` to `https://community.hachyderm.io/` makes the links absolute at build and, from my testing, does not affect URLs in dev mode.

Change `baseURL` value in config to fix RSS feed links

---

.github/workflows/publish.yml

according to https://github.com/actions/deploy-pages/issues/45 we should probably just not run on "closed PR" events and only rely on push to main (because every PR ends up with a push to main anyway)

fix ci so that merges dont fail

---

community.hachyderm.io/README.md

Some light editing to the intro paragraph for **Building the website**, added a note that users must connect via SSH (not HTTPS), added a link to the GitHub how-to doc, and put the notes into list form.

Clarify using SSH for building the website

---

community.hachyderm.io/content/en/blog/incidents/2023-01-07-fritz-timeouts/index.md

I'm not actually a Mastodon Developer, just someone who has contributed a bunch in 2017 when I helped on switter.at as a moderator, so I got pretty familiar with how the codebase and system worked. I just know node.js really well, and wrote websocket servers in node.js and also in ruby eventmachine (for Pusher), and have dealt with their fickle scaling issues.

Correct description of @thisismissem in fritz timeouts post

---

community.hachyderm.io/content/en/docs/rule-explainer/_index.md

also removed a couple extra empty lines before paragraph titles, as there was only one in other similar places.

Fix a couple typos in rule explainer

---

community.hachyderm.io/content/en/docs/hachyderm/_index.md

In welcome section, link to server's rules is redirecting to a non existent section, so now I'm redirecting to rule explainer.
Right now the user faces this error:
After the changes the user will be redirected to:

fix: link to rules section

---

community.hachyderm.io/content/en/blog/incidents/2023-07-16-security-redis-cache-exposed/index.md

Contains our initial analysis and corrective actions for a security incident that took place on July 16, 2023.

Security incident analysis: Redis cache public internet exposure - Jul 16, 2023

---

.github/workflows/publish.yml

The "latest" hugo version (not guaranteed to build the site) was incremented from 0.139.4 to 0.139.5, however, 0.139.5 appears to result in a 404 when installing hugo. This pins the hugo version to the last known working hugo version.

Pin hugo version to 0.139.4 for publish workflow

---

.github/workflows/publish.yml
.tool-versions

This is pretty basic, but it'll help when contributing to both community.hachyderm.io and nivenly.org, as they use different hugo versions, so installing them through a version manager such as `asdf` simplifies things.
Rather than repeating the version twice, I parse the .tool-versions file for the hugo version, assuming we always use extended mode.

Feature: use .tool-versions
